apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathy
spec:
  selector:
    matchLabels:
      name: mathy
  template:
    metadata:
      labels:
        name: mathy
    spec:
      containers:
        - name: mathy
          image: glmdev/mathy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mathy-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: mathy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mathy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "mathy.glmdev.tech"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mathy-service
            port:
              number: 80
